import { Navbar } from './Navbar'
import { Footer } from './Footer'
import Head from 'next/head'
import styles from '../styles/Layout.module.css'

export const Layout = ({ children }) => {
  return (
    <div className={styles['layout-width']}>
      <Head>
        <title>Mi Blog sin nombre </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className={styles.container}>{children}</main>
      <Footer />
    </div>

  )
}
