import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Card } from '../components/Card'

import { getAllFilesMetadata } from '../lib/mdx'

// import Link from 'next/link'

export default function Home ({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mi Blog sin nombre</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a mi Blog, sin nombre aún.
        </h1>

        <p className={styles.description}>
          El mejor blog del mundo
          <code className={styles.code}>Para tirar código</code>
        </p>

        <div className={styles.grid}>
          {posts.map((post) => {
            return (
              <Card post={post} key={post.slug} />
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps () {
  const posts = await getAllFilesMetadata()

  // console.log(posts)

  return {
    props: { posts }
  }
}
